export enum EKafkaErrorCodes {
    NoError = 0,
    Unknown = 1,
    OffsetOutOfRange = 2,
    CorruptMessage = 3,
    UnknownTopicOrPartition = 4,
    InvalidFetchSize = 5,
    LeaderNotAvailable = 6,
    NotLeaderForPartition = 7,
    RequestTimedOut = 8,
    BrokerNotAvailable = 9,
    ReplicaNotAvailable = 10,
    MessageTooLarge = 11,
    StaleControllerEpochCode = 12,
    OffsetMetadataTooLarge = 13,
    NetworkException = 14,
    CoordinatorLoadInProgress = 15,
    CoordinatorNotAvailable = 16,
    NotCoordinator = 17,
  }